spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lib
    username: root
    password: rootroot
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /wsu
#logging:
#  level:
#    org.springframework.security: TRACE